# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/libkdepim' : '@same'
    'pim/pimcommon' : '@same'

Options:
  require-passing-tests-on: [ 'Linux/Qt5', 'FreeBSD/Qt5' ]

