# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kimap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/pimcommon' : '@same'
