# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kimap' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'libraries/ktextaddons': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux/Qt5', 'FreeBSD/Qt5' ]

